export const SONG_LIST_REQUEST = "SONG_LIST_REQUEST";
export const SONG_LIST_SUCCESS = "SONG_LIST_SUCCESS";
export const SONG_LIST_FAIL = "SONG_LIST_FAIL";

export const SONG_DETAILS_REQUEST = "SONG_DETAILS_REQUEST";
export const SONG_DETAILS_SUCCESS = "SONG_DETAILS_SUCCESS";
export const SONG_DETAILS_FAIL = "SONG_DETAILS_FAIL";
